In [22]:
import pandas as pd

In [23]:
import numpy as np

In [24]:
df=pd.DataFrame([['Shreya',7.8,'Painting','VIT',19],['Rishi',8.4,'Singing','Amrita',20],['Freddy',8.2,'Basketball','Manipal',18],['Darwin',9.4,'Football',np.nan,21],['Mason',8.7,'Cricket','IIT',20],['Raghav',7.5,'Drawing','NIT',18],['Basil',8.9,'Reading','Amity',19],['Jyotsana',9.5,'Dancing','VIT',22],['Shyam',8.1,'Chess','SRM',20],['Jhanvi',7.7,'Swimming','VIT',19]])
df.columns=['Name','GPA','Hobby','College','Age']
df

       Name  GPA       Hobby  College  Age
0    Shreya  7.8    Painting      VIT   19
1     Rishi  8.4     Singing   Amrita   20
2    Freddy  8.2  Basketball  Manipal   18
3    Darwin  9.4    Football      NaN   21
4     Mason  8.7     Cricket      IIT   20
5    Raghav  7.5     Drawing      NIT   18
6     Basil  8.9     Reading    Amity   19
7  Jyotsana  9.5     Dancing      VIT   22
8     Shyam  8.1       Chess      SRM   20
9    Jhanvi  7.7    Swimming      VIT   19

In [25]:
df.head()

     Name  GPA       Hobby  College  Age
0  Shreya  7.8    Painting      VIT   19
1   Rishi  8.4     Singing   Amrita   20
2  Freddy  8.2  Basketball  Manipal   18
3  Darwin  9.4    Football      NaN   21
4   Mason  8.7     Cricket      IIT   20

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     10 non-null     object
 1   GPA      10 non-null     float64
 2   Hobby    10 non-null     object
 3   College  9 non-null      object
 4   Age      10 non-null     int64
dtypes: float64(1), int64(1), object(3)
memory usage: 528.0+ bytes

In [27]:
df.describe()

             GPA        Age
count  10.000000  10.000000
mean    8.420000  19.600000
std     0.694102   1.264911
min     7.500000  18.000000
25%     7.875000  19.000000
50%     8.300000  19.500000
75%     8.850000  20.000000
max     9.500000  22.000000

In [35]:
df.loc[4]

Name         Mason
GPA            8.7
Hobby      Cricket
College        IIT
Age             20
Name: 4, dtype: object

In [29]:
df.isnull().any()

Name       False
GPA        False
Hobby      False
College     True
Age        False
dtype: bool

In [30]:
df.isnull().sum()

Name       0
GPA        0
Hobby      0
College    1
Age        0
dtype: int64

In [31]:
df['College']=df['College'].fillna(df['College'].mode()[0])

In [32]:
df

       Name  GPA       Hobby  College  Age
0    Shreya  7.8    Painting      VIT   19
1     Rishi  8.4     Singing   Amrita   20
2    Freddy  8.2  Basketball  Manipal   18
3    Darwin  9.4    Football      VIT   21
4     Mason  8.7     Cricket      IIT   20
5    Raghav  7.5     Drawing      NIT   18
6     Basil  8.9     Reading    Amity   19
7  Jyotsana  9.5     Dancing      VIT   22
8     Shyam  8.1       Chess      SRM   20
9    Jhanvi  7.7    Swimming      VIT   19